target 'IOSproj' do
    use_frameworks!
    pod 'SQLite.swift', '~> 0.10'
    pod 'JSONHelper', '~> 1.7'
    pod 'RestEssentials', '~> 1.0'
    pod 'Alamofire', '~> 3.4'
    pod 'SwiftyJSON'
    pod 'Restofire','~> 1.1'
end